### ISSUE TITLE
Fix for AttributeError: module 'base64' has no attribute 'decodestring'

### ISSUE THREAD

**Issue by ScootRay** [dtougas/sendyrsspub#11]
Greets,

I recently installed this wonderful piece of code to allow me to do RSS to Sendy.

Since I am using a newer version of Python (3.9) it kept throwing the above error. I was able to fix it by editing line 93 of feedparser.py (found in /usr/local/lib/python3.9/site-packages -- your error message will tell you where it is if it's different from this)

from:

    _base64decode = getattr(base64, 'decodebytes', base64.encodestring)

to:

    _base64decode = getattr(base64, 'decodebytes', base64.decodebytes)

...and it works now. Passing on in case others run into this issue.

Thanks.
Ray

**Comment by dtougas** [comment]
Thanks for the report! I see there is a newer version of the `feedparser` library. Would you be willing to test to see if that newer version of the library fixes the problem?

**Comment by ScootRay** [comment]
Absolutely, be happy to do so!

BTW, is there a way to do multiple feeds at once into one email newsletter?

Thanks,
Ray

**Comment by dtougas** [comment]
OK, cool. To test the newer version of `feedparser`, you would run `pip install --upgrade feedparser` and see if the problem goes away, and verify that everything still works properly. If it fails to work properly for some reason, you can revert back to the older version by running `pip install --upgrade feedparser== 5.2.1`. If the newer version works and fixes the problem, I can update the dependencies in `requirements.txt`. Let me know how it goes!

There currently isn't a way to pull multiple feeds into one newsletter.

**Comment by ScootRay** [comment]
Ayup! That did the trick, all good now matey.

Thank you!
Ray

P.S. I can solve the multiple feed issue by finding a tool that aggregates multiple feeds into one RSS feed  I figure.

**Comment by dtougas** [comment]
Thanks for confirming the version upgrade worked. I have updated the code to use the latest version.

https://github.com/dtougas/sendyrsspub/pull/13
