### ISSUE TITLE
entry.content.value not being passed to template?

### ISSUE THREAD

**Issue by ScootRay** [dtougas/sendyrsspub#12]
Greets,

I'm trying to parse specifically the `entry.content.value` field but for some reason it is not being passed through to the template? I can see it available in the feed test (and feedparser has it as a valid string). 

I can pass `entry.content` by itself but in doing so it includes all the extra code like 

`<p>[{'type': 'text/html', 'language': None, 'base': 'https://alongtheray.com/feed/', 'value': '<p>It happene` (truncated)

I just want to pass only the content of `entry.content.value` by itself without the extraneous data. Any idea how this is possible?

This is to email the content of a blog post rather than the summary.

Thanks!
Ray

**Comment by dtougas** [comment]
The first square bracket in your output there seems to indicate that `entry.content` is an array. You could try `entry.content.0.value` to take the first item from the array and output its value.

**Comment by ScootRay** [comment]
WOOT! That did the trick.

Many thanks for helping sort this out.

Do you accept donations or anything of the sort? Coffee? Beer? ; )

Ray

**Comment by dtougas** [comment]
No problem, happy to help out!

Donations are not required, however if you feel the need, I have updated the project page with a donation button. Either way, I appreciate the sentiment.

**Comment by ScootRay** [comment]
Sent! Enjoy and thank you for the help. : )
 
Ray

**Comment by dtougas** [comment]
Wow, that was very generous of you. Thanks, you made my day!
