### ISSUE TITLE
Feature: Preview in browser

### ISSUE THREAD

**Issue by da2x** [dtougas/sendyrsspub#3]

**Comment by dtougas** [comment]
Are you thinking that another command-line switch could be added to preview a template in a browser? Or did you have some other behavior in mind?

**Comment by da2x** [comment]
Yes, using https://docs.python.org/3.4/library/webbrowser.html maybe. Can use a file protocol and absolute path. Hard to check your work from reading HTML, you need to see it processed to actually make sure it's working before emailing thousands of people.

**Comment by dtougas** [comment]
You could always re-direct the output to a file and then open the file in your browser. My concern with the auto browser opening is that people will usually not have this installed on the same system as their browser. They will probably have it on a server somewhere (which is what I am doing). A solution like that would only work in a local development environment.
