### ISSUE TITLE
Just wanted to say thank you and share

### ISSUE THREAD

**Issue by ryantaylor16** [dtougas/sendyrsspub#4]
I am not overly technical nor do I consider myself challenged when it comes to scripting, but I was able to use your script and even establish some best practices that I thought you might like to read. I have linked back to this repo in the article as well. Great job and well done. [http://buysendy.com/rss-sendy/](http://buysendy.com/rss-sendy/)

If you'd like to link to the article, I would appreciate it and give my full permission.

**Comment by dtougas** [comment]
Thanks! That looks like a nicely detailed article.

I have updated the readme file with a link to your post.
