### ISSUE TITLE
Can I get a similar code for sendgrid?

### ISSUE THREAD

**Issue by washington-kibichii** [dtougas/sendyrsspub#5]

**Comment by dtougas** [comment]
I have no need for that feature myself at the moment, so I won't be adding it any time soon. If you are willing to fund development of that effort, then I would certainly be open to doing so.

**Comment by washington-kibichii** [comment]
Cool, can we continue this conversation on email?

**Comment by dtougas** [comment]
Sure, you can reach me at (damien at tougas dot net).
