### ISSUE TITLE
How to make Newsletter Subject incremental?

### ISSUE THREAD

**Issue by xianx** [dtougas/sendyrsspub#6]
At first thanks for this great solution. I have successfully implemented it and working fine. A great work!

How to make Newsletter Subject incremental?

Like Newsletter 01, Newsletter 02, Newsletter 03 and so on.

Thanks.

**Comment by dtougas** [comment]
Currently, the software does not have that capability built-in, but it wouldn't be that difficult to add yourself if you know a little Python. It could be done by adding some code to the `settings.py` file that generates a custom subject line, or you could do it with a shell script that calls the `sendyrsspub.py` script with a custom `--subject ...` parameter.
