### ISSUE TITLE
Is it possible to set email subject from the post title?

### ISSUE THREAD

**Issue by xianx** [dtougas/sendyrsspub#7]
Is it possible to set email subject from the post title for the rss?

**Comment by dtougas** [comment]
@xianx Yes, there is support for template variables in the subject, so you could use the post title to construct your email subject.

**Comment by xianx** [comment]
I think you are pointing adding subject to email template but I am talking about the email subject or email title that user will see on their email. 

The email subject is hard-coded in settings.py. How can I set email subject from the post title?

**Comment by dtougas** [comment]
The subject can use template template variables, just like the body of the message can.

**Comment by xianx** [comment]
@dtougas I am not very much familiar with python but has little programming knowledge. How can I set email subject from the post title? Can you give me some instruction?

**Comment by dtougas** [comment]
Assuming there is only one new post in your feed, you could try editing the `settings.py` file and setting the subject as follows:

```
'subject': 'Latest Post: {{ entries.0.title }}',
```

That variable would take the title from the first entry in the list and use it as the subject. I haven't fully tested this, as I am just writing this on-the-fly, but it should work.

**Comment by xianx** [comment]
> Assuming there is only one new post in your feed, you could try editing the `settings.py` file and setting the subject as follows:
> 
> ```
> 'subject': 'Latest Post: {{ entries.0.title }}',
> ```
> 
> That variable would take the title from the first entry in the list and use it as the subject. I haven't fully tested this, as I am just writing this on-the-fly, but it should work.

it works!
